# =============================================================================
# Argo Rollouts - Advanced Blue/Green & Canary Deployments
#
# Prerequisites:
#   kubectl create namespace argo-rollouts
#   kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
#
# Features:
#   - Automated rollback on metrics failure
#   - Gradual traffic shifting
#   - Analysis runs with Prometheus
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry/api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
  strategy:
    blueGreen:
      activeService: api
      previewService: api-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
          - templateName: success-rate
        args:
          - name: service-name
            value: api-preview
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: api-preview
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: api
---
# Analysis template - checks success rate before promotion
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 30s
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(http_requests_total{service="{{args.service-name}}", status=~"2.."}[5m])) 
            / 
            sum(rate(http_requests_total{service="{{args.service-name}}"}[5m]))
---
# Canary rollout alternative
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-canary
  template:
    metadata:
      labels:
        app: api-canary
    spec:
      containers:
        - name: api
          image: registry/api:latest
          ports:
            - containerPort: 3000
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: { duration: 2m }
        - setWeight: 25
        - pause: { duration: 2m }
        - setWeight: 50
        - pause: { duration: 5m }
        - setWeight: 100
      canaryService: api-canary
      stableService: api-stable
      trafficRouting:
        nginx:
          stableIngress: api-ingress
